# Environment

In this file an Environment class with three diffrent methodologies is cunstructed to face with our problem. This three types of modeling is helping us for a better ovecome to tackle this issue.

برای مدل‌سازی مسئله ما ۳ سناریو متفاوت را در ادامه بررسی خواهیم کرد.

سناریوی اول:
در این سناریو، محیط ما که قرار است استیت‌های شبکه را تشکیل دهد برابر با ماتریس ورودی درنظر می‌شود.

## First senario: 

State: ()

we define the input $D$ matrix as the observation
and for action, we get a random indeces of matrix and 

In [4]:
import numpy as np
from sklearn.decomposition import PCA

In [408]:
a = [\
     
    [0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0.],
    [0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1.],
    [0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0.],
    [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
    [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
    [0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1.],
    [0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1.],
    [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
    [0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0.],
    [0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1.],
    [1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0.],
    [0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0.],
    [0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1.]
]

In [409]:
m = np.array(a)

In [410]:
def measure(f):
    import timeit
    def wrapped(*args, **kwargs):
        tic = timeit.default_timer()
        ret = f(*args, **kwargs)
        toc = timeit.default_timer()
        print("TICTOC: {}".format((toc - tic)))
        return ret
    return wrapped
              
@measure             
def conflict(B):
    B = B.astype(np.uint8)
    N, M = B.shape[:2]
    confilicts = []
    for m1 in range(M):
        for m2 in range(m1+1, M):

            for c1 in range(N):
                if B[c1,m1]==0 and B[c1,m2]==0:
                    continue
                for c2 in range(c1+1, N):
                    for c3 in range(c2+1, N):
                        if B[c1,m1]+B[c2,m1]+B[c3,m1]!=2 or B[c1,m2]+B[c2,m2]+B[c3,m2]!=2:
                            continue

#                         Y = np.array([
#                             [B[c1,m1], B[c1,m2]],
#                             [B[c2,m1], B[c2,m2]],
#                             [B[c3,m1], B[c3,m2]],
#                         ])
#                         cond1 = np.sum(Y, axis=1).tolist() in [[1,1,2], [1,2,1], [2,1,1]]
#                         cond2 = np.sum(Y, axis=0).tolist() == [2,2]
 
                        if [B[c1,m1]+B[c1,m2],B[c2,m1]+B[c2,m2],B[c3,m1]+B[c3,m2]] in [[1,1,2],[1,2,1],[2,1,1]]:
                            confilicts.append((c1,c2,c3,m1,m2))

    return confilicts

In [411]:
len(conflict(m))

TICTOC: 0.08153662737458944


0

In [412]:
np.sum(m, axis=0).astype(int).tolist()

[1, 11, 1, 12, 2, 4, 10, 2, 5, 0, 5]

In [416]:
def sort_m(m):
    sum0 = np.sum(m, axis=0)
    sum1 = np.sum(m, axis=1)
    
    arg0 = np.argsort(sum0).astype(int).tolist()
    arg1 = np.argsort(sum1).astype(int).tolist()
    
    sorted_m = m[arg1, :][:, arg0[::-1]]
    
    print(sorted_m)

In [417]:
m

array([[0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0.],
       [0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1.],
       [1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1.]])

In [418]:
sort_m(m)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0.]]


res

# Data

In [ ]:
class Tree():
    pass

class TreeGenerator():
    pass

In [ ]:
class ActionSpace(object):
    """Defines the observation and action spaces, so you can write generic
    code that applies to any Env. For example, you can choose a random
    action.
    """
    def __init__(self, shape=None, dtype=None):
        import numpy as np  # takes about 300-400ms to import, so we load lazily
        self.shape = None if shape is None else tuple(shape)
        self.dtype = None if dtype is None else np.dtype(dtype)
        self.low = 0
        self.high = 1
        self._np_random = None

    def sample(self):
        """Randomly sample an element of this space. Can be 
        uniform or non-uniform sampling based on boundedness of space."""
        raise NotImplementedError

    def seed(self, seed=None):
        """Seed the PRNG of this space. """
        self._np_random, seed = seeding.np_random(seed)
        return [seed]
    
    
class ObservationSpace(object):
    def __init__(self, shape=None, dtype=None):
        import numpy as np  # takes about 300-400ms to import, so we load lazily
        self.shape = None if shape is None else tuple(shape)
        self.dtype = None if dtype is None else np.dtype(dtype)
        self.low = 0
        self.high = 1
        self._np_random = None

In [378]:
class Environment(object):
    def __init__(self, **params):
        self.__E = E
        self.__D = D
        self.__gamma = 0.9
        self.action_space = ActionSpace()
        self.observation_space = ObservationSpace()
        self.max_episode_step = ""
        
        N, M = params["N"], params["M"]
        generator = TreeGenerator(
            M, N,
            ZETA=1,
            Gamma=0.15,
            alpha=0.2,
            beta=0.08,
            MR=0.05,
            save_dir=False,
        )
        
        self.__tree = generator.generate()
        return
    
    def reset(self,):
        return obs
    
    def step(self, action):
        return obs, reward, done, info
    
    def seed(self, seed):
        pass
    
    def get_loss(self, B):
        c = self.conflict(B)
        l = self.likelihood(B)
        return c + self.__gamma*l
        
        
    def conflict(B):
        B = B.astype(np.uint8)
        N, M = B.shape[:2]
        confilicts = []
        for m1 in range(M):
            for m2 in range(m1+1, M):

                for c1 in range(N):
                    if B[c1,m1]==0 and B[c1,m2]==0:
                        continue
                    for c2 in range(c1+1, N):
                        for c3 in range(c2+1, N):
                            if B[c1,m1]+B[c2,m1]+B[c3,m1]!=2 or B[c1,m2]+B[c2,m2]+B[c3,m2]!=2:
                                continue

    #                         Y = np.array([
    #                             [B[c1,m1], B[c1,m2]],
    #                             [B[c2,m1], B[c2,m2]],
    #                             [B[c3,m1], B[c3,m2]],
    #                         ])
    #                         cond1 = np.sum(Y, axis=1).tolist() in [[1,1,2], [1,2,1], [2,1,1]]
    #                         cond2 = np.sum(Y, axis=0).tolist() == [2,2]

                            if [B[c1,m1]+B[c1,m2],B[c2,m1]+B[c2,m2],B[c3,m1]+B[c3,m2]] in [[1,1,2],[1,2,1],[2,1,1]]:
                                confilicts.append((c1,c2,c3,m1,m2))

        return confilicts

    
    def likelihood(self, B):
        E = self.__E
        a = self.__tree.get_alpha()
        b = self.__tree.get_beta()
        
        # N00 -> count([b=0]^[e=0])
        N00 = np.prod(B.shape[:2]) - np.count_nonzero(B+E)
        
        # N11 -> count([b=1]^[e=1])
        N11 = np.count_nonzero(B*E)
        
        # N01 -> count([b=0]^[e=1])
        N00 = np.count_nonzero( np.where((E-B)>0,1,0) )
        
        # N10 -> count([b=1]^[e=0])
        N11 = np.count_nonzero( np.where((B-E)>0,1,0) )
        
        # alpha^N10 * beta^N01 * (1-alpha)^N00 * (1-beta)^N11
        lh = a**N10 * b**N01 * (1-a)**N00 * (1-b)**N11
        
        return lh
        